EXAMJSFSTRUTS2/src/java/da/EventController.java
package da;

import da.util.JsfUtil;
import da.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("eventController")
@SessionScoped
public class EventController implements Serializable {

    private Event current;
    private DataModel items = null;
    @EJB
    private da.EventFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public EventController() {
    }

    public Event getSelected() {
        if (current == null) {
            current = new Event();
            selectedItemIndex = -1;
        }
        return current;
    }

    private EventFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Event) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Event();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EventCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Event) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EventUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Event) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EventDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Event getEvent(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Event.class)
    public static class EventControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EventController controller = (EventController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "eventController");
            return controller.getEvent(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Event) {
                Event o = (Event) object;
                return getStringKey(o.getPlanning());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Event.class.getName());
            }
        }

    }

}

EXAMJSFSTRUTS2/web/event/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateEventTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                   
                    <h:outputLabel value="#{bundle.CreateEventLabel_date}" for="date" />
                    <h:inputText id="date" value="#{eventController.selected.date}" title="#{bundle.CreateEventTitle_date}" >
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                  
                    
                    <h:outputLabel value="#{bundle.CreateEventLabel_time}" for="time" />
                    <h:inputText id="time" value="#{eventController.selected.time}" title="#{bundle.CreateEventTitle_time}" >
                        <f:convertDateTime pattern="HH:mm:ss" />
                    </h:inputText>
                   
                    
                    <h:outputLabel value="#{bundle.CreateEventLabel_planning}" for="planning" />
                    <h:inputText id="planning" value="#{eventController.selected.planning}" title="#{bundle.CreateEventTitle_planning}" required="true" requiredMessage="#{bundle.CreateEventRequiredMessage_planning}"/>
                   
                    
                    <h:outputLabel value="#{bundle.CreateEventLabel_address}" for="address" />
                    <h:inputText id="address" value="#{eventController.selected.address}" title="#{bundle.CreateEventTitle_address}" />
                    
                    
                    <h:outputLabel value="#{bundle.CreateEventLabel_info}" for="info" />
                    <h:inputTextarea id="info" value="#{eventController.selected.info}" title="#{bundle.CreateEventTitle_info}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{eventController.create}" value="#{bundle.CreateEventSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{eventController.prepareList}" value="#{bundle.CreateEventShowAllLink}" immediate="true"/>
                <br />
                <br />
                
            </h:form>
        </ui:define>
    </ui:composition>

</html>

EXAMJSFSTRUTS2/web/event/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditEventTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditEventLabel_planning}" for="planning" />
                    <h:inputText id="planning" value="#{eventController.selected.planning}" title="#{bundle.EditEventTitle_planning}" required="true" requiredMessage="#{bundle.EditEventRequiredMessage_planning}"/>
                    <h:outputLabel value="#{bundle.EditEventLabel_date}" for="date" />
                    <h:inputText id="date" value="#{eventController.selected.date}" title="#{bundle.EditEventTitle_date}" >
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditEventLabel_time}" for="time" />
                    <h:inputText id="time" value="#{eventController.selected.time}" title="#{bundle.EditEventTitle_time}" >
                        <f:convertDateTime pattern="HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditEventLabel_address}" for="address" />
                    <h:inputText id="address" value="#{eventController.selected.address}" title="#{bundle.EditEventTitle_address}" />
                    <h:outputLabel value="#{bundle.EditEventLabel_info}" for="info" />
                    <h:inputText id="info" value="#{eventController.selected.info}" title="#{bundle.EditEventTitle_info}" />
                </h:panelGrid>
                <h:commandLink action="#{eventController.update}" value="#{bundle.EditEventSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditEventViewLink}"/>
                <br />
                <h:commandLink action="#{eventController.prepareList}" value="#{bundle.EditEventShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditEventIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

EXAMJSFSTRUTS2/web/event/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListEventTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListEventEmpty}" rendered="#{eventController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{eventController.items.rowCount > 0}">
                    <h:outputText value="#{eventController.pagination.pageFirstItem + 1}..#{eventController.pagination.pageLastItem + 1}/#{eventController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{eventController.previous}" value="#{bundle.Previous} #{eventController.pagination.pageSize}" rendered="#{eventController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{eventController.next}" value="#{bundle.Next} #{eventController.pagination.pageSize}" rendered="#{eventController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{eventController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEventTitle_planning}"/>
                            </f:facet>
                            <h:outputText value="#{item.planning}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEventTitle_date}"/>
                            </f:facet>
                            <h:outputText value="#{item.date}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEventTitle_time}"/>
                            </f:facet>
                            <h:outputText value="#{item.time}">
                                <f:convertDateTime pattern="HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEventTitle_address}"/>
                            </f:facet>
                            <h:outputText value="#{item.address}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEventTitle_info}"/>
                            </f:facet>
                            <h:outputText value="#{item.info}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{eventController.prepareView}" value="#{bundle.ListEventViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{eventController.prepareEdit}" value="#{bundle.ListEventEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{eventController.destroy}" value="#{bundle.ListEventDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{eventController.prepareCreate}" value="#{bundle.ListEventCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListEventIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

EXAMJSFSTRUTS2/web/event/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewEventTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewEventLabel_planning}"/>
                    <h:outputText value="#{eventController.selected.planning}" title="#{bundle.ViewEventTitle_planning}"/>
                    <h:outputText value="#{bundle.ViewEventLabel_date}"/>
                    <h:outputText value="#{eventController.selected.date}" title="#{bundle.ViewEventTitle_date}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewEventLabel_time}"/>
                    <h:outputText value="#{eventController.selected.time}" title="#{bundle.ViewEventTitle_time}">
                        <f:convertDateTime pattern="HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewEventLabel_address}"/>
                    <h:outputText value="#{eventController.selected.address}" title="#{bundle.ViewEventTitle_address}"/>
                    <h:outputText value="#{bundle.ViewEventLabel_info}"/>
                    <h:outputText value="#{eventController.selected.info}" title="#{bundle.ViewEventTitle_info}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{eventController.destroyAndView}" value="#{bundle.ViewEventDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewEventEditLink}"/>
                <br />
                <h:commandLink action="#{eventController.prepareCreate}" value="#{bundle.ViewEventCreateLink}" />
                <br />
                <h:commandLink action="#{eventController.prepareList}" value="#{bundle.ViewEventShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewEventIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

EXAMJSFSTRUTS2/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>

    </h:body>



</html>

EXAMJSFSTRUTS2/web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>